import os
import sys
import glob
from pathlib import Path
from tqdm import tqdm

# Determine the absolute path to the root directory of the project
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Add the project root to the system path
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from state import WorkflowState, Paper, PaperAnalysis, TopicShema, Topic
from agents.base_agent import BaseAgent

class ETL(BaseAgent):
    def __init__(self):
        # Initialize ETL components if needed
        pass

    def run(self, state: WorkflowState):
        files = glob.glob("data/*")
        for paper_link in tqdm(files, total=len(files), desc="📄 Extracting papers:"):
            paper_analysis = self._transform(paper_link)
            state["elt_out"].append(Paper(link=paper_link, metadata=paper_analysis))

        state["topic_list"] = [
            Topic(name=TopicShema.Topic2, papers=[], citations=[]),
            Topic(name=TopicShema.Topic1, papers=[], citations=[]),
            Topic(name=TopicShema.Topic3, papers=[], citations=[]),
        ]

        return state

    def _extract(self, file_path):
        # This data was generated by the Gemini model.
        with open(Path(file_path), "r") as file:
            data = file.read()
        return data

    def _transform(self, paper_link):
        paper = self._extract(paper_link)
        response = self.parse_response(
            system_prompt=f"Extract relevant information from the data: {paper}",
            content=paper,
            response_format=PaperAnalysis,
        )
        return response


if __name__ == "__main__":
    import pickle

    etl = ETL()
    state = WorkflowState()
    state["elt_out"] = []
    etl.run(state)
    # print("ETL process completed. Extracted data:", state["elt_out"])

    # Save the state object as a pickle file
    with open("out/ETL.pkl", "wb") as pickle_file:
        pickle.dump(state, pickle_file)
